### ISSUE TITLE
Different input modes

### ISSUE THREAD

**Issue by danieltwagner** [favict/pico-waveform-generator#1]
Hi,

Thank you for making these additions to the original design!
I've wanted to use an OLED display and rotary encoder and put those changes in a new branch https://github.com/danieltwagner/pico-waveform-generator/tree/display

Would you be open to a pull request? I've tried to keep existing functionality in place as much as possible.

**Comment by favict** [comment]
Hi @danieltwagner, I'm glad you found this project useful and worked on improving it! Please, feel free to open a PR 🚀
